apiVersion: v2
name: nothingdns
description: A production-ready DNS server with DoH/DoT/DoQ support
version: 0.1.0
appVersion: v0.1.0
keywords:
  - dns
  - dnssec
  - doh
  - dot
  - doq
  - dns-server
home: https://nothingdns.github.io
sources:
  - https://github.com/NothingDNS/NothingDNS
maintainers:
  - name: NothingDNS
    email: nothingdns@example.com
