"""NothingDNS Python SDK — a typed client for the NothingDNS management API.

Quick start::

    import os
    from nothingdns import NothingDNSClient

    with NothingDNSClient("http://dns.example.com:8080") as client:
        client.auth.login(os.environ["NDNS_USER"], os.environ["NDNS_PASSWORD"])
        for zone in client.zones.list().zones:
            print(zone.name, zone.records)

The client is organised into namespaces that mirror the server's API groups
(``auth``, ``zones``, ``cache``, ``config``, ``acl``, ``blocklists``, ``rpz``,
``dnssec``, ``upstreams``, ``geoip``, ``cluster``, ``dashboard``, ``metrics``).
Every method returns a typed model and raises
:class:`~nothingdns.errors.NothingDNSApiError` on a 4xx/5xx response.
"""

from ._http import DEFAULT_BASE_URL, DEFAULT_TIMEOUT, Transport
from .auth import ROLES, AuthResource
from .client import (
    LOG_LEVELS,
    RPZ_ACTIONS,
    ACLResource,
    BlocklistsResource,
    CacheResource,
    ClusterResource,
    ConfigResource,
    DNSSECResource,
    DashboardResource,
    GeoIPResource,
    MetricsResource,
    NothingDNSClient,
    RPZResource,
    UpstreamsResource,
    ZonesResource,
    from_env,
)
from .errors import (
    NothingDNSApiError,
    NothingDNSConnectionError,
    NothingDNSError,
    NothingDNSValidationError,
    is_forbidden,
    is_not_found,
    is_rate_limited,
    is_unauthorized,
)
from .models import (
    ACLConfig,
    ACLRule,
    BlocklistSource,
    BlocklistStats,
    CacheStats,
    ClusterMetrics,
    ClusterNode,
    ClusterNodeList,
    ClusterStatus,
    ClusterSummary,
    CookieConfig,
    DNS64Config,
    DNSSECKey,
    DNSSECKeyList,
    DNSSECStatus,
    DashboardStats,
    GeoIPStats,
    GossipStats,
    HealthResponse,
    MetricsHistory,
    PTRBulkPreview,
    PTRBulkResult,
    PTRChange,
    PTRLookup,
    QueryEvent,
    QueryLogEntry,
    QueryLogPage,
    RaftStats,
    RecursionAllowList,
    Record,
    RecordList,
    Role,
    RPZRule,
    RPZRuleList,
    RPZStats,
    ServerConfig,
    Session,
    SOA,
    SlaveZone,
    StatusResponse,
    TopDomain,
    TopDomains,
    UpstreamHealth,
    UpstreamServer,
    Upstreams,
    User,
    Zone,
    ZoneDetail,
    ZoneList,
)

__version__ = "1.0.0"

__all__ = [
    "__version__",
    # client
    "NothingDNSClient",
    "from_env",
    "DEFAULT_BASE_URL",
    "DEFAULT_TIMEOUT",
    "Transport",
    # resources
    "AuthResource",
    "ZonesResource",
    "CacheResource",
    "ConfigResource",
    "ACLResource",
    "BlocklistsResource",
    "RPZResource",
    "DNSSECResource",
    "UpstreamsResource",
    "GeoIPResource",
    "ClusterResource",
    "DashboardResource",
    "MetricsResource",
    # constants
    "LOG_LEVELS",
    "ROLES",
    "RPZ_ACTIONS",
    # errors
    "NothingDNSError",
    "NothingDNSApiError",
    "NothingDNSConnectionError",
    "NothingDNSValidationError",
    "is_not_found",
    "is_unauthorized",
    "is_forbidden",
    "is_rate_limited",
    # models
    "ACLConfig",
    "ACLRule",
    "BlocklistSource",
    "BlocklistStats",
    "CacheStats",
    "ClusterMetrics",
    "ClusterNode",
    "ClusterNodeList",
    "ClusterStatus",
    "ClusterSummary",
    "CookieConfig",
    "DNS64Config",
    "DNSSECKey",
    "DNSSECKeyList",
    "DNSSECStatus",
    "DashboardStats",
    "GeoIPStats",
    "GossipStats",
    "HealthResponse",
    "MetricsHistory",
    "PTRBulkPreview",
    "PTRBulkResult",
    "PTRChange",
    "PTRLookup",
    "QueryEvent",
    "QueryLogEntry",
    "QueryLogPage",
    "RaftStats",
    "RecursionAllowList",
    "Record",
    "RecordList",
    "Role",
    "RPZRule",
    "RPZRuleList",
    "RPZStats",
    "ServerConfig",
    "Session",
    "SOA",
    "SlaveZone",
    "StatusResponse",
    "TopDomain",
    "TopDomains",
    "UpstreamHealth",
    "UpstreamServer",
    "Upstreams",
    "User",
    "Zone",
    "ZoneDetail",
    "ZoneList",
]
