package idna

import (
	"sort"
	"strings"
	"unicode"
)

// IDNA2008 label checks of RFC 5891 §5.4 over the RFC 5892 derived
// property (F627–F631). The Unicode data lives in tables<version>.go,
// generated by gen_idna_tables.go for the standard library's Unicode
// version (one file per supported toolchain, selected by build constraint).

// RFC 5892 derived property values (derivedRanges).
const (
	propUnassigned uint8 = iota
	propPVALID
	propContextJ
	propContextO
	propDisallowed
)

// Joining_Type values (joiningRanges); jtU also stands for C, which rule
// A.1 does not distinguish from U.
const (
	jtU uint8 = iota
	jtL
	jtD
	jtR
	jtT
)

// cccVirama is the Canonical_Combining_Class of a virama (RFC 5892 A.1,
// A.2).
const cccVirama = 9

// runeRange8 is one entry of a generated range table: code points lo..hi
// (inclusive) have value v.
type runeRange8 struct {
	lo, hi rune
	v      uint8
}

// decompEntry is a full canonical decomposition.
type decompEntry struct {
	r rune
	d string
}

// compEntry is a primary composite c of the pair (a, b).
type compEntry struct {
	a, b, c rune
}

func lookup8(t []runeRange8, r rune) uint8 {
	i := sort.Search(len(t), func(i int) bool { return t[i].hi >= r })
	if i < len(t) && t[i].lo <= r {
		return t[i].v
	}
	return 0
}

// derivedProperty returns the RFC 5892 derived property of r.
func derivedProperty(r rune) uint8 { return lookup8(derivedRanges[:], r) }

// joiningType returns the Joining_Type of a PVALID code point (jtU for
// every other code point).
func joiningType(r rune) uint8 { return lookup8(joiningRanges[:], r) }

// combiningClass returns the Canonical_Combining_Class of r.
func combiningClass(r rune) uint8 { return lookup8(cccRanges[:], r) }

// Hangul syllable constants (Unicode §3.12).
const (
	hangulSBase  = 0xAC00
	hangulLBase  = 0x1100
	hangulVBase  = 0x1161
	hangulTBase  = 0x11A7
	hangulLCount = 19
	hangulVCount = 21
	hangulTCount = 28
	hangulNCount = hangulVCount * hangulTCount
	hangulSCount = hangulLCount * hangulNCount
)

func decompose(r rune, out []rune) []rune {
	if s := r - hangulSBase; s >= 0 && s < hangulSCount {
		out = append(out, hangulLBase+s/hangulNCount, hangulVBase+(s%hangulNCount)/hangulTCount)
		if t := s % hangulTCount; t != 0 {
			out = append(out, hangulTBase+t)
		}
		return out
	}
	i := sort.Search(len(decompositions), func(i int) bool { return decompositions[i].r >= r })
	if i < len(decompositions) && decompositions[i].r == r {
		return append(out, []rune(decompositions[i].d)...)
	}
	return append(out, r)
}

func compose(a, b rune) (rune, bool) {
	// Hangul LV and LV+T.
	if l, v := a-hangulLBase, b-hangulVBase; l >= 0 && l < hangulLCount && v >= 0 && v < hangulVCount {
		return hangulSBase + (l*hangulVCount+v)*hangulTCount, true
	}
	if s, t := a-hangulSBase, b-hangulTBase; s >= 0 && s < hangulSCount && s%hangulTCount == 0 && t > 0 && t < hangulTCount {
		return a + t, true
	}
	i := sort.Search(len(compositions), func(i int) bool {
		e := compositions[i]
		return e.a > a || (e.a == a && e.b >= b)
	})
	if i < len(compositions) && compositions[i].a == a && compositions[i].b == b {
		return compositions[i].c, true
	}
	return 0, false
}

// nfc returns the Unicode Normalization Form C of s (UAX #15: canonical
// decomposition, canonical ordering, canonical composition).
func nfc(s string) string {
	buf := make([]rune, 0, len(s))
	for _, r := range s {
		buf = decompose(r, buf)
	}
	// Canonical ordering: stable insertion sort of each run of non-starters.
	for i := 1; i < len(buf); i++ {
		c := combiningClass(buf[i])
		if c == 0 {
			continue
		}
		for j := i; j > 0; j-- {
			p := combiningClass(buf[j-1])
			if p <= c {
				break
			}
			buf[j-1], buf[j] = buf[j], buf[j-1]
		}
	}
	if len(buf) == 0 {
		return ""
	}
	// Canonical composition.
	starter := 0
	last := combiningClass(buf[0])
	if last != 0 {
		starter = -1
		last = 0xFF // nothing composes with a leading non-starter
	}
	out := 1
	for i := 1; i < len(buf); i++ {
		r := buf[i]
		c := combiningClass(r)
		if starter >= 0 && (last < c || last == 0) {
			if comp, ok := compose(buf[starter], r); ok {
				buf[starter] = comp
				continue
			}
		}
		if c == 0 {
			starter = out
		}
		last = c
		buf[out] = r
		out++
	}
	return string(buf[:out])
}

// isNFC reports whether s is in Normalization Form C.
func isNFC(s string) bool { return nfc(s) == s }

// checkULabel applies the RFC 5891 §5.4 / §4.2.3 rules to one U-label
// (a decoded A-label or a mapped Unicode label): NFC, no "--" in positions
// 3 and 4, no leading or trailing hyphen, no leading combining mark, and
// every code point PVALID, or CONTEXTJ / CONTEXTO with its RFC 5892
// Appendix A rule satisfied. UNASSIGNED code points are rejected unless
// allowUnassigned. The Bidi rule is applied separately (it needs the whole
// domain name).
func checkULabel(label string, allowUnassigned bool) error {
	if !isNFC(label) {
		return ErrNotNFC
	}
	runes := []rune(label)
	if len(runes) >= 4 && runes[2] == '-' && runes[3] == '-' {
		return ErrHyphen34
	}
	if strings.HasPrefix(label, "-") {
		return ErrHyphenStart
	}
	if strings.HasSuffix(label, "-") {
		return ErrHyphenEnd
	}
	if len(runes) > 0 && isCombiningMark(runes[0]) {
		return ErrLeadingCombining
	}
	for i, r := range runes {
		switch derivedProperty(r) {
		case propPVALID:
		case propContextJ:
			if !contextJOK(runes, i) {
				return ErrContextJ
			}
		case propContextO:
			if !contextOOK(runes, i) {
				return ErrContextO
			}
		case propUnassigned:
			if !allowUnassigned {
				return ErrUnassigned
			}
		default:
			return ErrDisallowed
		}
	}
	return nil
}

// contextJOK applies RFC 5892 Appendix A.1 (ZERO WIDTH NON-JOINER) and A.2
// (ZERO WIDTH JOINER) to runes[i].
func contextJOK(runes []rune, i int) bool {
	// A.1/A.2: If Canonical_Combining_Class(Before(cp)) .eq. Virama Then True.
	if i > 0 && combiningClass(runes[i-1]) == cccVirama {
		return true
	}
	if runes[i] != 0x200C {
		return false // A.2: ZWJ only after a virama
	}
	// A.1: (Joining_Type:{L,D})(Joining_Type:T)*\u200C(Joining_Type:T)*(Joining_Type:{R,D})
	j := i - 1
	for j >= 0 && joiningType(runes[j]) == jtT {
		j--
	}
	if j < 0 {
		return false
	}
	if t := joiningType(runes[j]); t != jtL && t != jtD {
		return false
	}
	k := i + 1
	for k < len(runes) && joiningType(runes[k]) == jtT {
		k++
	}
	if k >= len(runes) {
		return false
	}
	t := joiningType(runes[k])
	return t == jtR || t == jtD
}

// contextOOK applies RFC 5892 Appendix A.3–A.9 to runes[i].
func contextOOK(runes []rune, i int) bool {
	r := runes[i]
	switch {
	case r == 0x00B7: // A.3 MIDDLE DOT: between two 'l'
		return i > 0 && i < len(runes)-1 && runes[i-1] == 'l' && runes[i+1] == 'l'
	case r == 0x0375: // A.4 GREEK LOWER NUMERAL SIGN (KERAIA): Greek after
		return i < len(runes)-1 && unicode.Is(unicode.Greek, runes[i+1])
	case r == 0x05F3 || r == 0x05F4: // A.5 GERESH, A.6 GERSHAYIM: Hebrew before
		return i > 0 && unicode.Is(unicode.Hebrew, runes[i-1])
	case r == 0x30FB: // A.7 KATAKANA MIDDLE DOT: label has Hiragana, Katakana or Han
		for j, c := range runes {
			if j != i && c != 0x30FB && unicode.In(c, unicode.Hiragana, unicode.Katakana, unicode.Han) {
				return true
			}
		}
		return false
	case r >= 0x0660 && r <= 0x0669: // A.8 ARABIC-INDIC DIGITS: no extended digits
		for _, c := range runes {
			if c >= 0x06F0 && c <= 0x06F9 {
				return false
			}
		}
		return true
	case r >= 0x06F0 && r <= 0x06F9: // A.9 EXTENDED ARABIC-INDIC DIGITS: no Arabic-Indic digits
		for _, c := range runes {
			if c >= 0x0660 && c <= 0x0669 {
				return false
			}
		}
		return true
	}
	return false // CONTEXTO code point without a rule (RFC 5891 §5.4 step 7)
}
