// Package idna implements Internationalized Domain Names in Applications (IDNA)
// according to RFC 5890, 5891, 5892, 5893, 5895, and RFC 3492 (Punycode).
//
// # Security limitations
//
// The Punycode codec (RFC 3492) is complete and overflow-hardened. Every
// U-label (a Unicode label or a decoded "xn--" A-label) is checked as
// RFC 5891 §5.4 requires: NFC, no "--" in positions 3 and 4, no leading
// combining mark, every code point PVALID or CONTEXTJ/CONTEXTO with its
// RFC 5892 Appendix A rule satisfied, and (per profile) the RFC 5893 Bidi
// rule. The RFC 5892 derived property, Bidi_Class, Joining_Type and the
// normalization data come from tables<version>.go, generated by
// gen_idna_tables.go for the Unicode version of the toolchain's standard
// library (F627–F631).
//
// Limitations:
//
//   - The RFC 5895 mapping applied to Unicode input is lower-casing plus
//     NFC; width (fullwidth/halfwidth) mapping is not applied, so such
//     characters are rejected as DISALLOWED instead of being mapped.
//   - No confusable/homograph detection is performed (that is a
//     display-layer concern per UTS #39, out of scope for a resolver).
//
// Do NOT rely on this package as the sole defense for security-critical
// name comparison or phishing prevention; it validates wire-level IDNA
// well-formedness, not visual spoofing resistance.
package idna

import (
	"errors"
	"fmt"
	"strings"
	"unicode"
)

// Errors returned by IDNA operations.
var (
	ErrEmptyLabel       = errors.New("empty label")
	ErrLabelTooLong     = errors.New("label too long")
	ErrNameTooLong      = errors.New("domain name too long")
	ErrInvalidRune      = errors.New("invalid rune for IDNA")
	ErrInvalidPunycode  = errors.New("invalid punycode")
	ErrInvalidACEPrefix = errors.New("invalid ACE prefix")
	ErrInvalidBid       = errors.New("bidirectional restriction violation")
	ErrContextJ         = errors.New("contextual rule J failure")
	ErrContextO         = errors.New("contextual rule O failure")
	ErrHyphenStart      = errors.New("label starts with hyphen")
	ErrHyphenEnd        = errors.New("label ends with hyphen")
	ErrDigitStart       = errors.New("label starts with digit")
	ErrLeadingCombining = errors.New("leading combining character")
	ErrDisallowed       = errors.New("disallowed character")
	ErrUnassigned       = errors.New("unassigned character")
	ErrHyphen34         = errors.New("label has hyphens in positions 3 and 4")
	ErrNotNFC           = errors.New("label is not in NFC")
)

// MaxLabelLength is the maximum length of a label (63 bytes per RFC 5891).
const MaxLabelLength = 63

// MaxNameLength is the maximum length of a domain name (255 bytes per RFC 5891).
const MaxNameLength = 255

// ACEPrefix is the ASCII-compatible encoding prefix for punycode.
const ACEPrefix = "xn--"

// Profile represents an IDNA profile with specific rules.
type Profile struct {
	// AllowUnassigned indicates whether unassigned code points are allowed.
	AllowUnassigned bool
	// UseSTD3Rules indicates whether to use STD3 ASCII rules.
	UseSTD3Rules bool
	// CheckBidi indicates whether to check bidirectional rules.
	CheckBidi bool
	// CheckJoiner has no effect: the RFC 5892 CONTEXTJ rules (A.1, A.2)
	// are always applied, as RFC 5891 §5.4 requires for lookup.
	CheckJoiner bool
}

// ToASCII converts an internationalized domain name to ASCII (punycode).
// This implements RFC 5891 Section 4.1. It applies the STD3 ASCII rules and
// the U-label checks of Profile.ToASCII, allows unassigned code points and
// performs no Bidi check; use Profile.ToASCII to choose those.
func ToASCII(domain string) (string, error) {
	return Profile{UseSTD3Rules: true, AllowUnassigned: true}.ToASCII(domain)
}

// ToASCII converts domain like the package-level ToASCII, applying the
// profile's options (F621):
//
//   - UseSTD3Rules: ASCII labels may hold only letters, digits and interior
//     hyphens. When false, any ASCII label of valid length is accepted
//     (for example service labels such as "_dmarc").
//   - AllowUnassigned: when false, a U-label (a Unicode label, or an
//     "xn--" A-label that decodes and re-encodes to itself) containing a
//     code point unassigned in the Go toolchain's Unicode tables is
//     rejected with ErrUnassigned (RFC 5891 §5.4).
//   - CheckBidi: the RFC 5893 §2 Bidi rule is applied to every label of a
//     Bidi domain name; a violation returns ErrInvalidBid.
//   - CheckJoiner has no effect: CONTEXTJ is always checked.
//
// A Unicode label is mapped (lower-cased, then NFC) and an "xn--" label
// must be a valid A-label (RFC 5891 §5.4, F624): it must decode to a
// non-ASCII label that re-encodes to the same Punycode and holds no
// control, surrogate, private-use or space code points; otherwise ToASCII
// fails with ErrInvalidPunycode or ErrDisallowed. Every resulting U-label
// must then pass the RFC 5891 §5.4 checks (F627–F631): NFC (ErrNotNFC), no
// "--" in positions 3 and 4 (ErrHyphen34), no leading or trailing hyphen,
// no leading combining mark (ErrLeadingCombining), no DISALLOWED code point
// (ErrDisallowed), and the RFC 5892 Appendix A rules for CONTEXTJ
// (ErrContextJ) and CONTEXTO (ErrContextO) code points. ASCII labels that
// are not A-labels are not U-labels and only get the STD3 check.
func (p Profile) ToASCII(domain string) (string, error) {
	domain = strings.TrimSpace(domain)
	domain = strings.TrimSuffix(domain, ".")

	if domain == "" {
		return "", nil
	}

	// ulabels holds every label in Unicode form (decoded A-labels, mapped
	// Unicode labels, ASCII labels as-is) for the profile checks.
	var ulabels []string

	// Check if already ASCII-only
	if isASCII(domain) {
		// Enforce RFC 1035 §2.3.4 / RFC 5891 §4.4 length limits on the
		// pure-ASCII path. Previously this branch fell through to
		// `validateSTD3` per label, which only checks character classes
		// and hyphen placement — a 256-byte ASCII domain or a 200-byte
		// single label both slipped through, leaving downstream code
		// (cache key sizing, zone radix tree, NSEC bitmap) to discover
		// the violation later. The non-ASCII path already checked total
		// length at the end; harmonize the rules across both paths.
		if len(domain) > MaxNameLength {
			return "", ErrNameTooLong
		}
		labels := strings.Split(domain, ".")
		for _, label := range labels {
			if label == "" {
				return "", ErrEmptyLabel
			}
			if len(label) > MaxLabelLength {
				return "", ErrLabelTooLong
			}
			if p.UseSTD3Rules {
				if err := validateSTD3(label); err != nil {
					return "", err
				}
			}
			u, err := aLabelToU(label)
			if err != nil {
				return "", err
			}
			ulabels = append(ulabels, u)
		}
		if err := p.checkULabels(ulabels); err != nil {
			return "", err
		}
		return domain, nil
	}

	// Step 1: Encode with punycode
	labels := strings.Split(domain, ".")
	result := make([]string, 0, len(labels))

	for _, label := range labels {
		if label == "" {
			return "", ErrEmptyLabel
		}

		// Mapping may turn a Unicode label into plain ASCII.
		if !isASCII(label) {
			label = mapLabel(label)
		}
		// Try to encode the label
		if isASCII(label) {
			// ASCII label — enforce label-length cap. The pure-ASCII
			// fast-path above already does this, but the mixed path
			// (one IDNA + several ASCII labels) flows through here
			// without ever calling validateSTD3 on the ASCII labels.
			if len(label) > MaxLabelLength {
				return "", ErrLabelTooLong
			}
			if p.UseSTD3Rules {
				if err := validateSTD3(label); err != nil {
					return "", err
				}
			}
			u, err := aLabelToU(label)
			if err != nil {
				return "", err
			}
			result = append(result, label)
			ulabels = append(ulabels, u)
		} else {
			// Non-ASCII label - convert to punycode
			encoded, err := encodeLabel(label)
			if err != nil {
				return "", fmt.Errorf("label %q: %w", label, err)
			}
			aceLabel := ACEPrefix + encoded
			// Post-encoding length check: a short Unicode label can
			// expand past 63 ASCII bytes after punycode + xn-- prefix.
			if len(aceLabel) > MaxLabelLength {
				return "", ErrLabelTooLong
			}
			result = append(result, aceLabel)
			ulabels = append(ulabels, label)
		}
	}

	// Check total length
	asciiDomain := strings.Join(result, ".")
	if len(asciiDomain) > MaxNameLength {
		return "", ErrNameTooLong
	}
	if err := p.checkULabels(ulabels); err != nil {
		return "", err
	}

	return asciiDomain, nil
}

// aLabelToU returns the Unicode form of an ASCII label: the decoded U-label
// for an "xn--" A-label, the label itself for any other label. An "xn--"
// label that is not a valid A-label is rejected (RFC 5891 §5.4, F624): it
// must decode to a non-ASCII string that re-encodes to the same Punycode
// (compared case-insensitively), and the decoded label must not contain
// control, surrogate, private-use or space code points (DISALLOWED by
// RFC 5892 in every U-label).
func aLabelToU(label string) (string, error) {
	if len(label) < len(ACEPrefix) || !strings.EqualFold(label[:len(ACEPrefix)], ACEPrefix) {
		return label, nil
	}
	suffix := strings.ToLower(label[len(ACEPrefix):])
	decoded := decodePunycode(suffix)
	if decoded == "" || isASCII(decoded) || encodePunycode(decoded) != suffix {
		return "", fmt.Errorf("label %q: %w", label, ErrInvalidPunycode)
	}
	for _, r := range decoded {
		if unicode.In(r, unicode.Cc, unicode.Cs, unicode.Co, unicode.Z) {
			return "", fmt.Errorf("label %q: %w", label, ErrDisallowed)
		}
	}
	return decoded, nil
}

// checkULabels applies the U-label checks (checkULabel, with the profile's
// AllowUnassigned) to every non-ASCII label and, with CheckBidi, the Bidi
// rule to the whole domain name, given the Unicode form of every label.
func (p Profile) checkULabels(ulabels []string) error {
	for _, l := range ulabels {
		if isASCII(l) {
			continue
		}
		if err := checkULabel(l, p.AllowUnassigned); err != nil {
			return fmt.Errorf("label %q: %w", l, err)
		}
	}
	if p.CheckBidi {
		return checkBidiRule(ulabels)
	}
	return nil
}

// ToUnicode converts an ASCII domain name (possibly with punycode) to Unicode.
// This implements RFC 5891 Section 4.2. Labels that are not A-labels are
// returned unchanged (no STD3 check); every "xn--" label must be a valid
// A-label whose U-label passes the checks of Profile.ToASCII (unassigned
// code points allowed, like ToASCII), and the Bidi rule is applied to the
// whole name (F630). A Unicode label in the input is mapped and checked
// the same way.
func ToUnicode(domain string) (string, error) {
	return Profile{AllowUnassigned: true, CheckBidi: true}.ToUnicode(domain)
}

// ToUnicode converts domain to Unicode like the package-level ToUnicode,
// applying the profile's options as Profile.ToASCII does (UseSTD3Rules to
// the ASCII labels that are not A-labels). An invalid A-label is an error,
// never decoded as-is (F630).
func (p Profile) ToUnicode(domain string) (string, error) {
	domain = strings.TrimSpace(domain)
	domain = strings.TrimSuffix(domain, ".")

	if domain == "" {
		return "", nil
	}

	labels := strings.Split(domain, ".")
	result := make([]string, 0, len(labels))
	for _, label := range labels {
		if label == "" {
			return "", ErrEmptyLabel
		}
		if !isASCII(label) {
			label = mapLabel(label)
		}
		if isASCII(label) && p.UseSTD3Rules {
			if err := validateSTD3(label); err != nil {
				return "", err
			}
		}
		u, err := aLabelToU(label)
		if err != nil {
			return "", err
		}
		result = append(result, u)
	}
	if err := p.checkULabels(result); err != nil {
		return "", err
	}
	return strings.Join(result, "."), nil
}

// encodeLabel encodes a Unicode label to punycode.
func encodeLabel(label string) (string, error) {
	// For non-ASCII labels (Internationalized labels):
	// 1. Map characters (RFC 5895)
	// 2. Check if any non-ASCII characters remain
	// 3. Encode with punycode
	// Note: Bidirectional rules (RFC 5893) apply to the ASCII output, not input

	// Step 1: Apply mapping (lowercase, etc.)
	mapped := mapLabel(label)

	// Check if any non-ASCII characters remain after mapping
	needsEncoding := false
	for _, r := range mapped {
		if r > 0x7F {
			needsEncoding = true
			break
		}
	}

	if !needsEncoding {
		// All ASCII after mapping - validate with STD3
		if err := validateSTD3(mapped); err != nil {
			return "", err
		}
		return mapped, nil
	}

	// Step 2: Encode with punycode
	encoded := encodePunycode(mapped)

	return encoded, nil
}

// decodeLabel decodes a punycode label (the bytes after the "xn--" ACE
// prefix) to Unicode per RFC 3492 §6.2.
//
// Format: optional ASCII prefix, single '-' delimiter, then the encoded
// suffix. If there is no '-', the entire label is the encoded suffix (the
// ASCII prefix is empty). The previous implementation split on "--" — that
// is not the punycode delimiter and produced "no encoding part" for every
// real punycode label, leaving Unicode names un-decoded.
func decodeLabel(punycode string) (string, error) {
	if punycode == "" {
		return "", ErrEmptyLabel
	}
	return decodePunycode(punycode), nil
}

// mapLabel applies the RFC 5895 mapping to a Unicode label: upper case to
// lower case (§2 step 1), then Normalization Form C (step 3, F631). Width
// mapping (step 2) is not applied.
func mapLabel(label string) string {
	var result strings.Builder
	for _, r := range label {
		result.WriteRune(unicode.ToLower(r))
	}
	return nfc(result.String())
}

// validateLabel validates a label according to IDNA rules. An ASCII label
// must satisfy the STD3 rules; with isIDNA an "xn--" label must also be a
// valid A-label and its decoded U-label is validated like a Unicode label
// (F623, F624). A Unicode label is rejected unless isIDNA.
func validateLabel(label string, isIDNA bool) error {
	if label == "" {
		return ErrEmptyLabel
	}

	if len(label) > MaxLabelLength {
		return ErrLabelTooLong
	}

	if isASCII(label) {
		if err := validateSTD3(label); err != nil {
			return err
		}
		if !isIDNA {
			return nil
		}
		u, err := aLabelToU(label)
		if err != nil {
			return err
		}
		if u == label {
			return nil
		}
		label = u
	} else if !isIDNA {
		return ErrInvalidRune
	}
	return validateULabel(label)
}

// validateULabel applies the RFC 5891 §5.4 U-label checks (checkULabel,
// unassigned code points rejected) and — for an RTL label — the RFC 5893
// §2 Bidi rule. A label that is not RTL is checked by the Bidi rule only as
// part of a Bidi domain name (see ValidateDomain), since the rule does not
// apply outside one.
func validateULabel(label string) error {
	if err := checkULabel(label, false); err != nil {
		return err
	}
	// RFC 5893 §2 Bidi rule: the same implementation Profile.ToASCII uses.
	if isRTLLabel(label) && !bidiLabelOK(label) {
		return ErrInvalidBid
	}
	return nil
}

// validateSTD3 validates a label against STD3 ASCII rules.
// Label must:
// - Not start with hyphen
// - Not end with hyphen
// - Not contain other ASCII special characters
func validateSTD3(label string) error {
	if len(label) == 0 {
		return nil
	}

	// Check start and end hyphens
	if label[0] == '-' {
		return ErrHyphenStart
	}
	if label[len(label)-1] == '-' {
		return ErrHyphenEnd
	}

	// Check for invalid ASCII characters
	for i := 0; i < len(label); i++ {
		c := rune(label[i])
		if c < 0x20 || c == 0x7F {
			return ErrInvalidRune
		}
		// Allow only letters, digits, and hyphens
		if !((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '-') {
			return ErrInvalidRune
		}
	}

	return nil
}

// isCombiningMark reports whether r is a combining mark (General_Category
// M: Mn, Mc or Me), which may not start a U-label (RFC 5891 §4.2.3.2).
func isCombiningMark(r rune) bool {
	return unicode.In(r, unicode.Mn, unicode.Mc, unicode.Me)
}

// isASCII returns true if string contains only ASCII characters.
func isASCII(s string) bool {
	for _, c := range s {
		if c > 0x7F {
			return false
		}
	}
	return true
}

// ValidateLabel validates a single DNS label for IDNA compliance.
// Labels longer than 63 bytes or containing invalid characters return errors.
func ValidateLabel(label string) error {
	return validateLabel(label, true)
}

// ValidateDomain validates an entire domain name for IDNA compliance.
func ValidateDomain(domain string) error {
	domain = strings.TrimSpace(domain)
	domain = strings.TrimSuffix(domain, ".")

	if domain == "" {
		return nil
	}

	if len(domain) > MaxNameLength {
		return ErrNameTooLong
	}

	labels := strings.Split(domain, ".")
	ulabels := make([]string, 0, len(labels))
	for _, label := range labels {
		if label == "" {
			return ErrEmptyLabel
		}
		if err := validateLabel(label, true); err != nil {
			return fmt.Errorf("label %q: %w", label, err)
		}
		u, err := aLabelToU(label)
		if err != nil {
			return err
		}
		ulabels = append(ulabels, u)
	}

	// RFC 5893 §2: in a Bidi domain name every label, LTR ones included,
	// must satisfy the Bidi rule.
	return checkBidiRule(ulabels)
}

// FromUnicode converts a Unicode domain name to ASCII (punycode).
// Alias for ToASCII.
func FromUnicode(domain string) (string, error) {
	return ToASCII(domain)
}

// FromASCII converts an ASCII domain name (possibly with punycode) to Unicode.
// Alias for ToUnicode.
func FromASCII(domain string) (string, error) {
	return ToUnicode(domain)
}
